### ISSUE TITLE
Request to customise the HttpClient in APIHTTPConnector

### ISSUE THREAD

**Issue by Stexxen** [zoho/zohocrm-java-sdk-7.0#3]
Hi, This is a feature request.

I would like to have the ability to customise the Apache HttpClient created in the function getHttpClient() within APIHTTPConnector.

I have a few reasons for this request.
1. Making the HostnameVerifier more secure, it's currently set to `NoopHostnameVerifier`
2. Forcing the TLS version and changing the cipher list.
3. Adding an Interceptor

These settings are not just for your endpoint, but also for the Proxy endpoint.

Thanks,
S.

**Comment by raja-7453** [comment]
@Stexxen Please get in touch with [support@zohocrm.com](mailto:support@zohocrm.com), for further updates. We will follow up on this request, over there.
Thanks!

**Comment by Stexxen** [comment]
Hi @raja-7453 Thanks for working and _completing_ this, but I can't see a commit. Can you provide so I can see the changes?

**Comment by raja-7453** [comment]
Hi @Stexxen, Please forward your requirements to [support@zohocrm.com](support@zohocrm.com)
